openapi: 3.0.0

info:
  title: Ï‰ bbs
  version: 0.0.0

servers:
  - url: https://xn--omega.com/api

paths:
  /posts/{post_id}:
    get:
      tags:
        - Post
      parameters:
        - name: post_id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Post"

components:
  schemas:
    Post:
      type: object
      properties:
        id:
          type: number
        title:
          type: string
