openapi: 3.0.0
info:
  title: Ï‰ bbs
  version: 0.0.0
servers:
  - url: https://xn--omega.com/api
paths:
  /me:
    get:
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                type: object
